ruby:
  default: "2.1.2"
  deploy_user: "youreallyshouldchangethis"
  versions:
    - "2.1.2"
  dependencies:
    - build-essential
    - openssl
    - libreadline6
    - libreadline6-dev
    - curl
    - git-core
    - zlib1g
    - zlib1g-dev
    - libssl-dev
    - libyaml-dev
    - libsqlite3-0
    - libsqlite3-dev
    - sqlite3
    - libxml2-dev
    - libxslt1-dev
    - autoconf
    - libc6-dev
    - libncurses5-dev
    - automake
    - libtool
    - bison
    - subversion
    - exuberant-ctags
    - libreadline-dev
