- debug: var=rbenv

- name: Installs rbenv
  sudo_user: "{{ ruby.deploy_user }}"
  sudo: yes
  git: repo=https://github.com/sstephenson/rbenv.git dest=~{{ ruby.deploy_user }}/.rbenv accept_hostkey=true

- name: Ensure fragments bash dir exists
  sudo_user: "{{ ruby.deploy_user }}"
  sudo: yes
  file: dest=~{{ ruby.deploy_user }}/.bash.d/ state=directory

- name: Installs rbenv bash file
  copy: src=50_rbenv.bash dest=~{{ ruby.deploy_user }}/.bash.d/50_rbenv.bash mode=700 owner={{ ruby.deploy_user }}

- name: Source rbenv bash file in dot bashrc
  sudo_user: "{{ ruby.deploy_user }}"
  sudo: yes
  lineinfile: dest=~{{ ruby.deploy_user }}/.bash_profile regexp="^source ~/\.bash\.d/50_rbenv\.bash" insertafter=EOF line="source ~/.bash.d/50_rbenv.bash" create=yes

- name: Creates plugin directory
  file: path=~{{ ruby.deploy_user }}/.rbenv/plugins/ owner={{ ruby.deploy_user }} group={{ ruby.deploy_user }} mode=0755 state=directory

- name: Installs ruby-build
  sudo_user: "{{ ruby.deploy_user }}"
  sudo: yes
  git: repo=git://github.com/sstephenson/ruby-build.git dest=~{{ ruby.deploy_user }}/.rbenv/plugins/ruby-build accept_hostkey=true

